"""
Download the UI fonts (Zen Maru Gothic + JetBrains Mono) from Google Fonts and
bundle them locally so MediaHotKey works fully offline — no CDN at runtime.

We keep the `latin` + `latin-ext` subsets (the interface is English; any CJK
track names fall back to the OS font). Run:

    python assets/fetch_fonts.py

Outputs:
    mediahotkey/web/fonts/*.woff2   the font files
    mediahotkey/web/fonts.css       @font-face rules (referenced by styles.css)
"""

import os
import re
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
WEB = os.path.join(ROOT, "mediahotkey", "web")
FONT_DIR = os.path.join(WEB, "fonts")

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120 Safari/537.36")

FAMILIES = {
    "Zen Maru Gothic": ("zen-maru-gothic", "Zen+Maru+Gothic"),
    "JetBrains Mono": ("jetbrains-mono", "JetBrains+Mono"),
}
WEIGHTS = [400, 500, 700]
KEEP_SUBSETS = {"latin", "latin-ext"}


def _get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def _parse_blocks(css):
    """Yield (subset, weight, url, unicode_range) per @font-face block.

    Google emits a `/* subset */` comment before each block."""
    parts = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    for i in range(1, len(parts) - 1, 2):
        subset = parts[i].strip()
        block = parts[i + 1]
        w = re.search(r"font-weight:\s*(\d+)", block)
        u = re.search(r"src:\s*url\(([^)]+)\)", block)
        r = re.search(r"unicode-range:\s*([^;]+);", block)
        if w and u:
            yield subset, int(w.group(1)), u.group(1), (r.group(1).strip() if r else "")


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    faces = []
    for label, (slug, qname) in FAMILIES.items():
        url = (f"https://fonts.googleapis.com/css2?family={qname}"
               f":wght@{';'.join(str(w) for w in WEIGHTS)}&display=swap")
        css = _get(url).decode("utf-8")
        for subset, weight, woff_url, urange in _parse_blocks(css):
            if subset not in KEEP_SUBSETS or weight not in WEIGHTS:
                continue
            fname = f"{slug}-{subset}-{weight}.woff2"
            data = _get(woff_url)
            with open(os.path.join(FONT_DIR, fname), "wb") as fh:
                fh.write(data)
            print(f"  {fname}  ({len(data) // 1024} KB)")
            rng = f"\n  unicode-range: {urange};" if urange else ""
            faces.append(
                "@font-face {\n"
                f"  font-family: '{label}';\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight};\n"
                "  font-display: swap;\n"
                f"  src: url('./fonts/{fname}') format('woff2');{rng}\n"
                "}"
            )

    with open(os.path.join(WEB, "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write("/* Locally bundled UI fonts — generated by assets/fetch_fonts.py */\n\n")
        fh.write("\n".join(faces) + "\n")
    print("wrote", os.path.join(WEB, "fonts.css"))


if __name__ == "__main__":
    main()
